In [1]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("dataset_chunk_1.csv")

In [3]:
data

,symbol,timestamp,open,high,low,close,volume,oi
0,SMARTLINK,2023-12-26 05:37:00+00:00,171.50,171.50,171.50,171.50,0,0
1,SMARTLINK,2023-12-26 05:39:00+00:00,171.50,171.50,171.50,171.50,0,0
2,SMARTLINK,2023-12-26 05:43:00+00:00,171.50,171.50,171.50,171.50,0,0
3,SMARTLINK,2023-12-26 05:48:00+00:00,171.50,171.50,170.70,170.70,50,0
4,SMARTLINK,2023-12-26 05:49:00+00:00,170.70,170.70,170.70,170.70,0,0
...,...,...,...,...,...,...,...,...
999995,SMLT,2022-10-18 06:59:00+00:00,120.65,120.65,120.65,120.65,0,0
999996,SMLT,2022-10-18 07:00:00+00:00,120.65,121.30,120.50,121.30,14,0
999997,SMLT,2022-10-18 07:01:00+00:00,121.30,121.40,120.50,121.40,49,0
999998,SMLT,2022-10-18 07:02:00+00:00,121.40,121.45,120.85,121.25,128,0
999999,SMLT,2022-10-18 07:03:00+00:00,121.25,121.30,121.25,121.30,1,0

In [4]:
data["target"] = data.groupby("symbol")["close"].shift(-1)

In [5]:
data.shape

(1000000, 9)

In [6]:
data.isnull().sum()

symbol       0
timestamp    0
open         0
high         0
low          0
close        0
volume       0
oi           0
target       6
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   symbol     1000000 non-null  object
 1   timestamp  1000000 non-null  object
 2   open       1000000 non-null  float64
 3   high       1000000 non-null  float64
 4   low        1000000 non-null  float64
 5   close      1000000 non-null  float64
 6   volume     1000000 non-null  int64
 7   oi         1000000 non-null  int64
 8   target     999994 non-null   float64
dtypes: float64(5), int64(2), object(2)
memory usage: 68.7+ MB

In [8]:
data.describe()

,open,high,low,close,volume,oi,target
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.0,999994.000000
mean,656.593339,656.991660,656.182225,656.593724,7.899136e+02,0.0,656.596191
std,910.849245,911.478844,910.182716,910.848513,7.207787e+03,0.0,910.850499
min,9.260000,9.260000,9.250000,9.260000,0.000000e+00,0.0,9.260000
25%,66.900000,66.940000,66.820000,66.900000,0.000000e+00,0.0,66.900000
50%,159.470000,159.500000,159.430000,159.470000,5.000000e+00,0.0,159.470000
75%,981.600000,982.000000,981.100000,981.600000,1.530000e+02,0.0,981.600000
max,4736.800000,4743.000000,4729.000000,4738.400000,1.784400e+06,0.0,4738.400000

In [9]:
print("\nDuplicate rows:", data.duplicated().sum())

Duplicate rows: 0

In [10]:
data = data.drop("timestamp", axis=1)

In [11]:
le = LabelEncoder()
data["symbol"] = le.fit_transform(data["symbol"])

In [12]:
data

        symbol    open    high     low   close  volume  oi  target
0            0  171.50  171.50  171.50  171.50       0   0  171.50
1            0  171.50  171.50  171.50  171.50       0   0  171.50
2            0  171.50  171.50  171.50  171.50       0   0  170.70
3            0  171.50  171.50  170.70  170.70      50   0  170.70
4            0  170.70  170.70  170.70  170.70       0   0  170.70
...        ...     ...     ...     ...     ...     ...  ..     ...
999995       5  120.65  120.65  120.65  120.65       0   0  121.30
999996       5  120.65  121.30  120.50  121.30      14   0  121.40
999997       5  121.30  121.40  120.50  121.40      49   0  121.25
999998       5  121.40  121.45  120.85  121.25     128   0  121.30
999999       5  121.25  121.30  121.25  121.30       1   0     NaN

[1000000 rows x 8 columns]

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   symbol  1000000 non-null  int64
 1   open    1000000 non-null  float64
 2   high    1000000 non-null  float64
 3   low     1000000 non-null  float64
 4   close   1000000 non-null  float64
 5   volume  1000000 non-null  int64
 6   oi      1000000 non-null  int64
 7   target  999994 non-null   float64
dtypes: float64(5), int64(3)
memory usage: 61.0 MB

In [14]:
data.isnull().sum()

symbol    0
open      0
high      0
low       0
close     0
volume    0
oi        0
target    6
dtype: int64

In [15]:
data["target"] = data["target"].fillna(0)

In [16]:
x= data.drop("target",axis = 1)
y= data["target"]

In [17]:
x

        symbol    open    high     low   close  volume  oi
0            0  171.50  171.50  171.50  171.50       0   0
1            0  171.50  171.50  171.50  171.50       0   0
2            0  171.50  171.50  171.50  171.50       0   0
3            0  171.50  171.50  170.70  170.70      50   0
4            0  170.70  170.70  170.70  170.70       0   0
...        ...     ...     ...     ...     ...     ...  ..
999995       5  120.65  120.65  120.65  120.65       0   0
999996       5  120.65  121.30  120.50  121.30      14   0
999997       5  121.30  121.40  120.50  121.40      49   0
999998       5  121.40  121.45  120.85  121.25     128   0
999999       5  121.25  121.30  121.25  121.30       1   0

[1000000 rows x 7 columns]

In [18]:
y

0         171.50
1         171.50
2         170.70
3         170.70
4         170.70
           ...
999995    121.30
999996    121.40
999997    121.25
999998    121.30
999999      0.00
Name: target, Length: 1000000, dtype: float64

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [22]:
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [23]:
y_pred = rf_model.predict(X_test)

In [24]:
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

Mean Absolute Error: 0.7973607700264401
Mean Squared Error: 6.712319433589854
R² Score: 0.9999918673440625

In [27]:
from sklearn.metrics import r2_score

# Train predictions
y_train_pred = rf_model.predict(X_train)

# Test predictions
y_test_pred = rf_model.predict(X_test)

# R2
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print("Training R²:", train_r2)
print("Testing R²:", test_r2)
print("R² Difference:", train_r2 - test_r2)

Training R²: 0.9999750849828424
Testing R²: 0.9999918673440625
R² Difference: -1.678236122015786e-05

In [28]:
# Save model and scaler
import joblib
joblib.dump(rf_model, 'rf_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']